envs:
- key: teste
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:5k+tJEqm6RtcpWfgzYq7y1eMBvoKQv0r:dou92AT6T2ORWmF1EWT0+esGqC00qCo=]

name: agent
region: nyc
ingress:
  rules:
    - component:
        name: website
      match:
        path:
          prefix: /
# - component:
  #     name: api
  #   match:
  #     path:
  #       prefix: /api

services:
static_sites:
  - name: website
    environment_slug: html
    github:
      branch: main
      deploy_on_push: true
      repo: felipear89/agent
    build_command: npm install && npm run build
    catchall_document: index.html
    source_dir: /frontend
    output_dir: ./dist

  # - name: api
  #   environment_slug: go
  #   # autoscaling:
  #   #   min_instance_count: 1
  #   #   max_instance_count: 2
  #   #   metrics:
  #   #     cpu:
  #   #       percent: 90
  #   instance_count: 1
  #   alerts:
  #     - rule: CPU_UTILIZATION
  #       disabled: false
  #       operator: GREATER_THAN
  #       value: 75
  #       window: FIVE_MINUTES
  #   envs:
  #     - key: GIN_MODE
  #       value: release
  #       scope: RUN_TIME
  #       type: GENERAL
  #     - key: SECRET_KEY
  #       value: secret123
  #       type: SECRET
  #   github:
  #     repo: felipear89/agent
  #     branch: main
  #     deploy_on_push: true
  #   source_dir: backend
  #   instance_size_slug: apps-s-1vcpu-0.5gb


