name: sample-monorepo

services:
  - name: api
    environment_slug: go
    github:
      repo: felipear89/agent
      branch: main
      deploy_on_push: true
    source_dir: api
    routes:
      - path: /api
