name: agent
region: nyc
ingress:
  rules:
    - component:
        name: website
      match:
        path:
          prefix: /
    # - component:
    #     name: api
    #   match:
    #     path:
    #       prefix: /api

# services:
#   - name: api
#     environment_slug: go
#     instance_count: 1
#     envs:
#       - key: GIN_MODE
#         value: release
#         scope: RUN_TIME
#         type: GENERAL
#     github:
#       repo: felipear89/agent
#       branch: main
#       deploy_on_push: true
#     source_dir: backend
#     instance_size_slug: apps-s-1vcpu-0.5gb

static_sites:
  - name: website
    environment_slug: html
    github:
      branch: main
      deploy_on_push: true
      repo: felipear89/agent
    build_command: npm install && npm run build
    catchall_document: index.html
    source_dir: frontend
    output_dir: ./dist


