name: Delete Preview

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  closed:
    runs-on: ubuntu-latest
    steps:
      - name: Delete preview app
        uses: digitalocean/app_action/delete@v2
        with:
          from_pr_preview: "true"
          ignore_not_found: "true"
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Delete branch
        if: github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.merged == false
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const branch = context.payload.pull_request.head.ref;
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `heads/${branch}`,
              });
              console.log(`Branch ${branch} deleted`);
            } catch (error) {
              console.log(`Branch not deleted: ${error.message}`);
            }
